"""Chapter 1 Batch 3: P314-P354 (Delimitations end, Definitions of Key Terms)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from save_translations import save_batch

T = {
    "314": "In such a structure, strategic choices do not immediately converge according to a single efficiency criterion, and judgments formed after training requests tend to be reinterpreted within multiple value criteria and stakeholder interests. Consequently, even when judgments exist, situations can arise where they do not connect to immediate decision-making agenda items. Such an institutional environment is treated not merely as a declared analytical \u2018limitation,\u2019 but as a concrete analytical context in which the conditions under which judgment\u2013decision conversion is delayed or stagnates can be observed. The resulting explanations correspond not to the presentation of general laws detached from specific organizational environments, but to the work of reconceptualizing the operating mechanisms of conversion structures revealed within those environments as theoretical categories.",

    "315": "Definitions",

    "316": "This section is established to clarify the semantic scope of core concepts repeatedly used throughout this study and to ensure consistency in conceptual usage across the analytical process. In particular, this study does not verify the effects after AI utilization training has been \u2018conducted,\u2019 but rather analyzes the phenomenon whereby judgments formed during the process of AI utilization capability enhancement training being \u2018requested, planned, and promoted\u2019 at the organizational level fail to convert into decision-making. Accordingly, rather than adopting terms as used in existing prior research wholesale, the semantic scope is explicitly realigned to correspond with this study\u2019s problem consciousness and unit of analysis (organizational level).",

    "317": "The term definitions presented in this section take existing prior research\u2019s conceptual definitions as their theoretical starting point, while explicitly distinguishing at the sentence level: (1) statements grounded in existing research definitions and discussions, and (2) the operational definitions employed in this study (Yin, 2009; Eisenhardt, 1989).",

    "318": "These term definitions serve not merely as conceptual explanations but function to prevent conceptual confusion or excessive generalization that may arise in subsequent chapters (Chapters 2\u20135) by clearly delineating the analytical boundary and argumentative scope of this study. Terms defined in this section are used consistently with the same meaning throughout this entire study, and subsequent chapters reference these definitions without redefinition (Yin, 2009).",

    "319": "1.9.1. AI Utilization Training",

    "320": "Here, \u2018AI utilization training\u2019 does not refer to simple technical training that transmits the mechanical usage of specific artificial intelligence tools to organizational members. In the extension of discussions in which existing studies have understood training as an intentional learning intervention designed to elicit changes in perception and behavior within organizations (Creswell, 2018), it is defined as a training intervention designed with the purpose of capability formation for integrating AI into actual work performance and decision-making processes throughout the organization.",

    "321": "This refers to an educational intervention structured to induce substantive changes in how members perceive, interpret, and act upon environmental changes, transcending the mere acquisition of specific operational skills. However, in the concrete context to which the analysis applies, AI utilization training is not confined to programs whose \u2018delivery has been completed.\u2019 Rather, it broadly encompasses the state in which its \u2018necessity\u2019 has been documented in official records at the organizational level and has passed through approval lines to be placed at the \u2018request and planning\u2019 stage. In this study, \u2018AI utilization training request\u2019 refers to the state in which the necessity for AI utilization training has been documented as an official organizational document (official correspondence) and has passed through the approval line, which is explicitly distinguished from the state in which the training program has actually been executed. The analytical object of this study is not the period after training has been conducted, but rather the process whereby, after the training request has been approved, the associated judgment converts into (or fails to convert into) formal decision-making.",

    "322": "Consequently, the work of directly comparing or evaluating the specific content of training programs, invested time, operational methods, or the degree of improvement in members\u2019 proficiency is thoroughly excluded. At this juncture, AI utilization training functions as a critical precondition (contextual trigger) that allows observation of how the organization\u2019s internal judgment structures respond, are legitimated, and are reconfigured. That is, it is treated as an institutional introduction occasion that stimulates the existing judgment and decision-making systems entrenched within the organization, thereby revealing whether conversion structures are operative.",

    "323": "1.9.2. Organizational Performance",

    "324": "In this study, \u2018organizational performance\u2019 is not confined to financial performance indicators. Particularly in the nonprofit organizational context, organizational performance has been discussed as a concept encompassing multidimensional elements including the degree of organizational purpose achievement, efficiency of resource utilization, quality of decision-making, and organizational sustainability (Ebrahim & Rangan, 2014). This perspective is consistent with recent research trends emphasizing that nonprofit organizational performance cannot be reduced to a single indicator (Benjamin et al., 2023).",

    "325": "In this study, the level or increase/decrease of organizational performance is neither directly measured nor causally verified. Organizational performance is not established as a dependent variable in this study; it is used only as an outcome context for explaining why the stagnation is perceived as problematic when judgments regarding the necessity of AI utilization capability enhancement (training introduction) have been formed yet fail to convert into formal decision-making.",

    "326": "1.9.3. Judgment",

    "327": "In this study, \u2018judgment\u2019 does not signify an individual\u2019s immediate choice or subjective perception. In existing research, judgment has been understood as the process whereby specific information or possibilities are constituted and legitimated as subjects of strategic consideration at the organizational level (Felin et al., 2015).",

    "328": "In this study, judgment is defined as the collective process whereby, at the pre-decision stage, specific information, possibilities, or problem awareness at the organizational level are recognized, interpreted, and legitimated as subjects of strategic consideration. Judgment does not signify an individual\u2019s immediate choice or subjective perception; the core criterion of judgment is whether the necessity of AI utilization capability enhancement (training introduction) is recognized as a viable option worthy of review within the organization. That judgment has been formed means that the relevant possibility has acquired the institutional qualification to become a subject of discussion, review, deferral, or adoption within the organization, but it does not yet signify that formal decision-making has taken place.",

    "329": "1.9.4. Decision-Making",

    "330": "Here, \u2018decision-making\u2019 refers to the formal act of choice that occurs after judgment has been formed, denoting decisions that entail organizational-level approval procedures and resource allocation. This aligns with the context in which existing organizational theories have explained decision-making as a process of choice institutionalized in the form of strategies, policies, procedures, budgets, and the like (Cohen et al., 1972; March & Olsen, 1976).",

    "331": "The core problematic is directed toward the phenomenon whereby, even after judgments have been clearly formed within the organization, those judgments stagnate within the organization without connecting to the stages of formal approval and resource allocation.",

    "332": "Consequently, approaches that evaluate the efficiency of decision-making or final outcomes are excluded from the analysis. Instead, the processual operations themselves\u2014whereby substantive conversion is not initiated or is interrupted midway in the conversion interval between judgment and decision-making\u2014are rigorously established as the central object of analysis.",

    "333": "1.9.5. Micro-level Mechanism",

    "334": "In this study, \u2018micro-level mechanism\u2019 does not refer to an individual\u2019s psychological state or a single act, but rather to the pattern of connection between judgment\u2013interpretation\u2013justification\u2013selection that is repeatedly observed within organizations\u2014that is, the operational logic at the process level through which judgments lead to or are blocked from becoming decision-making. Existing research has explained that macroscopic outcomes are generated through repeatedly observed patterns of recognition, interpretation, and action within organizations (Felin et al., 2015).",

    "335": "In this study, micro-level mechanism is defined as the repeatedly observed pattern of connection between judgment\u2013interpretation\u2013justification\u2013selection within organizations\u2014that is, the operational logic at the process level through which judgments lead to or are blocked from becoming decision-making. This perspective is consistent with the strategy-as-practice perspective, which holds that strategy and decision-making are constituted not as outcomes but as practice (Jarzabkowski et al., 2007). It also connects with discussions that micro-level actions, interactions, and routines generate organizational flexibility and change (Feldman & Pentland, 2003).",

    "336": "1.9.6. Dynamic Capabilities and Seizing",

    "337": "In this study, dynamic capabilities take Dynamic Capabilities Theory as their theoretical starting point (Teece, 1997; Teece, 2007). Dynamic capabilities have been discussed as the capacity enabling strategic change through organizations\u2019 integration and reconfiguration of resources in response to environmental change (Eisenhardt & Martin, 2000; Helfat et al., 2007).",

    "338": "This study does not comprehensively analyze the entire process of dynamic capabilities (sensing\u2013seizing\u2013transforming), but rather confines its analytical focus to the seizing stage among them. Seizing is understood as the capability of converting recognized opportunities into formal decision-making and resource allocation (Teece, 2007; Winter, 2003).",

    "339": "In this study, seizing is conceptualized not as a simple capacity for choice, but as the structural capability of legitimating and fixing judgments formed within the organization into formal decisions. Furthermore, it is understood as a product of the judgment structure that constitutes and legitimates at the organizational level what is to be regarded as a strategic option (Felin et al., 2015).",

    "340": "1.9.7. Theoretical Generalization",

    "341": "In this study, \u2018theoretical generalization\u2019 does not refer to probabilistically generalizing the results of a case study to a population. In existing qualitative research methodology, theoretical generalization has been explained as presenting an explanatory framework reviewable in analogous contexts by refining the relationships and processes derived from a single case to the level of concepts, constructs, and propositions (Eisenhardt, 1989; Yin, 2009).",

    "342": "This constitutes a means of complementing the limitations of single case studies, and makes explicit that case studies possess academic value through theoretical contribution rather than statistical representativeness (Flyvbjerg, 2006).",

    "343": "1.9.8. Non-decision / Non-event",

    "344": "In this study, Non-decision and Non-event are analytical concepts for explaining the state in which, despite judgments having been formed within the organization, those judgments have not converted into formal decision-making or execution. This study does not use the two terms as synonymous expressions referring to the same phenomenon, but employs them as a conceptual distinction for capturing conversion failure from different analytical angles. In existing organizational theory, the state in which decision-making has not occurred has also been understood as a result of power, institutions, and agenda-setting (Bachrach & Baratz, 1962). In particular, the process whereby certain matters do not reach the arena of discussion or dissipate without being placed on agendas is regarded not as \u2018the absence of decision\u2019 but as an organizational outcome.",

    "345": "Furthermore, in organizational research, it has been discussed that a state in which important changes or choices have not occurred\u2014that is, a Non-event\u2014can also be a subject of analysis (Collier, 2011). This is premised on the perspective that, rather than being excluded from analysis on the grounds that no observable behavior or outcomes exist, why such events did not occur is a subject requiring explanation.",

    "346": "In this study, Non-decision / Non-event is defined as the state in which, despite judgments regarding the necessity of AI utilization capability enhancement (training introduction) having been formed within the organization, those judgments have not entered formal decision-making procedures or progressed to the stages of agenda-setting, assignment of responsible parties, or resource allocation. Here, Non-decision refers to the state in which judgments, even after being formed, have not entered formal decision-making procedures, while Non-event refers to the state in which such conversion failure has not manifested as a visible event or decision over the passage of time. This signifies not the absence of judgment, but rather conversion failure occurring at the post-judgment stage, and is used as the conceptual reference point for empirically capturing the stagnation of the judgment\u2013decision-making conversion mechanism that constitutes the core analytical object of this study.",

    "347": "1.9.9. Seizing Stagnation (or Seizing Non-initiation)",

    "348": "In this study, Seizing Stagnation refers to the state in which the seizing stage described in Dynamic Capabilities Theory is not substantively initiated within the organization, or stagnates immediately after initiation. In existing research, seizing has been explained as a core capability for converting recognized opportunities into strategic choices and resource allocation (Teece, 2007; Winter, 2003). However, such conversion does not always occur automatically; the operation of seizing can be triggered or blocked by structural and institutional conditions within the organization.",

    "349": "In this study, Seizing Stagnation is conceptualized as the state in which, despite judgments having been formed, those judgments stagnate without being fixed as formal decision-making, due to failure in agenda-setting, ambiguity of responsible parties, absence of procedural initiation, and the like. This is understood not as \u2018failure\u2019 of seizing per se, but rather as a state in which the seizing stage has not been institutionally initiated (non-initiation) or procedural progress has been halted after initiation (stagnation).",

    "350": "Accordingly, in this study, Seizing Stagnation is not reducible to deficiencies in individual capabilities or lack of decision-makers\u2019 will. Rather, it is interpreted as a result of the judgment structure and institutional configuration that define at the organizational level what is legitimated as a strategic option and under what conditions conversion to decision-making occurs (Felin et al., 2015).",

    "351": "1.9.10. Process Tracing",

    "352": "In this study, Process Tracing is a core analytical method for temporally and processually tracing the process whereby judgments, after being formed, fail to convert into decision-making. Process tracing has been defined as a qualitative analytical method that systematically traces the intermediate stages and causal linkages constituting the process whereby a specific outcome has occurred or has not occurred, rather than a simple correlational analysis of variables (Bennett & Checkel, 2015; Collier, 2011).",

    "353": "In existing research, it has been emphasized that through process tracing, not only \u2018what occurred\u2019 but also \u2018why it did not occur\u2019 can be explained (Collier, 2011). This constitutes an approach particularly well-suited for analyzing non-events such as the Non-decision and Seizing Stagnation addressed in this study.",

    "354": "In this study, Process Tracing is employed to reconstruct, stage by stage, at what procedural points the judgment was delayed, halted, or blocked after judgments regarding the necessity of AI utilization capability enhancement (training introduction) were formed, centering on the event sequence and whether institutional initiation occurred. Through this, the study seeks to explain the mechanism whereby judgment\u2013decision-making conversion fails not through individual actors\u2019 intentions or post hoc interpretation, but through the arrangement and connective structure of processes internal to the organization (Eisenhardt, 1989; Bennett & Checkel, 2015)."
}

save_batch('translations_ch1_batch3.json', T)
