"""Chapter 2 Batch 2: P421-P452 (AI Adoption cont'd, Knowing-Doing Gap, Research Gap, Summary)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from save_translations import save_batch

T = {
    "421": "Prior research addressing AI adoption and utilization has generally positioned AI as a core technological resource for enhancing organizational performance and securing competitive advantage. In particular, studies converging with the discourse on digital transformation have understood AI not merely as an object of technological adoption, but as a catalyst for organizational transformation that reconfigures the entirety of organizational work processes, information processing modes, and strategy formulation procedures (Teece, 2007).",

    "422": "Within this research stream, AI adoption is redefined not as a question of \u2018whether to adopt,\u2019 but as a question of what strategic choices the organization makes subsequent to adoption. A substantial body of research explains that AI technology can enhance organizational strategic agility by improving the speed of decision-making, strengthening data-driven judgment, and augmenting operational efficiency (Eisenhardt & Martin, 2000). From this perspective, AI utilization is regarded as a core element that reinforces organizational Sensing and Transforming, and is consequently understood as potentially leading to organizational transformation and performance improvement.",

    "423": "However, this stream of prior research harbors a common limitation. Specifically, it shares the assumption that\u2014beginning not from mere AI technology adoption per se but from the \u2018AI utilization training request\u2019 as the starting point\u2014the judgments and strategic alternatives formed within the organization traverse the internal multi-layered approval systems and complex conflict mediation stages unimpeded, arriving at visible outcome creation along a linear trajectory. In other words, a unilinear transition logic is implicitly embedded at the foundation: that organizational-level judgment, once established, is immediately reduced to a strategic resolution, and the ensuing choice promptly results in resource reallocation and tangible outcomes without delay.",

    "424": "Under the analytical conditions dominated by such outcome-centered assumptions, critical processual dimensions are inevitably marginalized. Namely, the micro-level dynamics of intermediate stages\u2014how a particular judgment is constructed through what interpretive contestation and legitimation sequences among internal actors immediately after AI utilization training is requested of the organization, and furthermore, how the specific pathway through which that judgment is incorporated into the formal decision-making trajectory or subjected to delay, deferral, and even cessation at particular bottleneck points actually operates\u2014are displaced from the principal objects of inquiry. Consequently, the critical conversion zone interposed between the establishment of judgment and the derivation of formal decision tends to be treated as an already-traversed fait accompli rather than as an object of explanation that must be rigorously dissected to illuminate the essence of the phenomenon.",

    "425": "2.4.2. Research on the Relationship Between AI Utilization Capabilities and Organizational Performance",

    "426": "A principal stream of the existing literature illuminating the phenomenon of artificial intelligence adoption has been concentrated on identifying the correlation between AI-based capabilities accumulated within organizations and ultimate visible performance outcomes. This approach establishes as its core inquiry the question of what relational networks are formed between technical assets acquired through training and learning processes, data-driven analytical insights, and algorithmic control levels on the one hand and objective organizational output indicators on the other. In this process, the perspective that conceptualizes artificial intelligence as a constituent element of organizational dynamic capabilities has argued that AI-related capabilities enhance the Sensing function vis-\u00e0-vis the external environment and the Transforming mechanism of internal resources, thereby ultimately generating sustainable competitive advantage (Teece, 2007).",

    "427": "Nevertheless, a substantial number of these prior discussions expose the limitation of disproportionately concentrating analytical weight on verifying the superficial association between the degree to which capabilities are accumulated and post hoc performance indicators. When the focus of inquiry is calibrated exclusively to the two extremes of \u2018whether capability exists\u2019 and \u2018whether outcomes are produced,\u2019 the complex internal conversion trajectory linking those two points is severely compressed or omitted. In other words, even if meaningful knowledge and skills have been accumulated among individual members and across the organization beginning from the AI utilization training request, the processual dimension of in-depth dissection\u2014regarding through what procedural gatekeeping and approval systems the said capability solidifies into final strategic decision-making, or alternatively, at precisely which point it is delayed, deferred, or stagnated\u2014remains insufficient.",

    "428": "This analytical gap engenders the logical fallacy that capability acquisition and formal decision derivation lie on a seamless single continuum, and entrenches the uncritical expectation that organizational-level judgment, once established, will invariably culminate in strategic resolution without delay. Yet when the view is narrowed to the interior of concrete organizational environments in practice, patterns are frequently observed in which judgment on a particular matter fails to be elevated to a formal agenda, fails to acquire a legitimation structure capable of persuading internal stakeholders, or drifts in a state where the responsible party to guarantee execution remains unspecified. The procedural delays, logical inconsistencies, and entrenchment of non-decision phenomena generated within the zone between AI utilization attempts and actual organizational outcomes are complex products that can never be explained solely by departmental execution limitations or external environmental constraints.",

    "429": "Consequently, the capability\u2013performance-centered explanatory framework upon which the existing AI adoption and utilization discourse has relied demonstrates its failure to fully theorize the critical intermediate conversion zone in which internal judgment is transformed into formal decision-making that binds the entire organization. This theoretical deficit is directly connected to the core problematic awareness of establishing as the highest-priority analytical object the internal mechanism itself by which judgments articulated immediately after AI utilization training requests fail to align with the strategic decision-making trajectory. Accordingly, departing from the perspective that reduces the Seizing stage to a mere product of choice behavior, the present study seeks to reconceptualize it as a bifurcation mechanism through which formed judgments either transition into substantive decisions or remain in a state of stagnation, thereby comprehensively reexamining the unilinear conversion logic that prior research has uncritically assumed.",

    "430": "2.5. The Knowing\u2013Doing Gap and the Research Gap in the Seizing Mechanism",

    "431": "The prior literature illuminating the adoption and utilization of artificial intelligence and the attendant organizational transformation phenomena has generally regarded AI-related technology and utilization capabilities as key variables determining corporate performance creation and strategic advantage. In this context, artificial intelligence is apprehended as a strategic resource that transcends a mere functional auxiliary tool and drives fundamental change in internal decision-making systems and overall work processes. The theoretical claim that capabilities accumulated from the AI utilization training request directly contribute to the enhancement of organizational dynamic capabilities is also situated along this extension (Teece, 2007).",

    "432": "However, beneath this mainstream approach lies a specific unilinear logic that is implicitly embedded. Namely, the vague expectation is assumed that so long as meaningful knowledge and skills are accumulated among internal members through training requests, the acquired capabilities will immediately result in strategic resolutions and tangible outcomes without traversing the organization\u2019s complex internal coordination procedures. In other words, the transition zone between the stage of acquiring something (knowing) and the stage of actually executing it (doing) has been treated not as an independent object that must be meticulously decomposed to grasp the essence of the phenomenon, but as a fait accompli that is smoothly traversed once certain conditions are met (Eisenhardt & Martin, 2000; Teece, 2007).",

    "433": "Yet in concrete organizational environments in practice, instances are frequently observed in which judgment on a particular matter has been distinctly established, yet it fails to settle into formal decision-making that binds the entire organization. Such a gap left unattended between cognition and decision cannot be reduced to a mere matter of task delays within the implementing department; it must be newly investigated as a structural and processual bottleneck phenomenon in which formed judgment fails to enter the trajectory of internal institutional approval.",

    "434": "Among the principal studies that have traced AI adoption phenomena based on actual cases, the AIDA doctoral dissertation produced at the University of Glasgow has three-dimensionally dissected, from the perspective of Dynamic Capabilities Theory, the manner in which AI-based analytical capabilities are incubated and acquire legitimacy in the organizational depths (Lee, 2025). That literature particularly delves into the preconditions for the operation of the Sensing and Transforming stages, precisely capturing the ramifications that technological initiatives exert on the organization\u2019s formal structures and processes. However, Lee (2025), as a study targeting AI analytical capability building in accounting firms, presents contextual differences from the decision-making structures of public and nonprofit organizations. Moreover, that study concentrated its analysis on the Sensing and Transforming stages, and did not establish the micro-level process of judgment converting into formal decision-making at the Seizing stage as an independent unit of analysis\u2014a point that partially supports the analytical gap of the present study.",

    "435": "Analogous limitations are commonly found in other prior studies on artificial intelligence adoption and utilization. While abundant discussion has accumulated regarding the structural design of training programs, specific learning content, and the typologization of derived capabilities, the structural-level explanation revealing under what institutional conditions judgment established within the organization immediately after training requests is formally approved or deferred remains severely deficient. Ultimately, the intermediate approval zone obstructing the space between judgment and final performance indicators has failed to be analytically dissected with rigor, and the tendency to reduce it to a peripheral variable of the execution stage has not been transcended (Lee, 2025; Teece, 2007).",

    "436": "The concept of the Knowing\u2013Doing Gap, which has been substantively addressed in the organizational learning and organizational behavior discourses, provides an exceedingly useful theoretical clue for elucidating such neglected disconnection zones (Pfeffer & Sutton, 2000). This concept identifies a structural contradictory state in which an organization has clearly secured specific knowledge and meaningful information assets at the organizational level, yet these do not translate into substantive organizational action or binding decisions.",

    "437": "Within the present inquiry context, this gap phenomenon is not restricted to a term denoting individual members\u2019 lack of will or simple deficiency in execution capacity. Rather, it is comprehensively reconstructed as a core analytical frame for systematically dissecting the pattern in which judgment that has settled within the organization beginning from the AI utilization training request drifts or becomes entrenched in an invisible state within the organization, having failed to successfully pass through the formal institutional approval gateway (Pfeffer & Sutton, 2000).",

    "438": "This problem is also confirmed in the existing discourse on organizational Dynamic Capabilities Theory, particularly regarding the Seizing stage. Dynamic Capabilities Theory presents the processes of Sensing, Seizing, and Transforming, yet Seizing frequently tends to be summarized as the outcome of strategic choice (Teece, 2007). Consequently, the processual explanation regarding through what approval rules judgment is confirmed as decision-making has been relatively diminished (Eisenhardt & Martin, 2000).",

    "439": "An analogous research gap is identified in the Korean organizational context as well. Domestic studies have addressed organizational performance associated with AI and digital transformation (Kwon & Yang, 2022) or the relationship between organizational learning and performance (Jeong, 2017), yet no research has been identified that establishes the micro-level mechanism by which organizational judgment converts into formal decision-making after an AI utilization training request as an independent analytical object. This suggests a research gap that exists in common both domestically and internationally.",

    "440": "In synthesis, the existing research on AI adoption, utilization, and organizational transformation reveals a shared gap in failing to systematically analyze, at the mechanism level, the intermediate zone in which judgments formed after AI utilization training requests convert into strategic decision-making. Research connecting the problematic awareness of the Knowing\u2013Doing Gap with the Seizing stage of Dynamic Capabilities Theory to analyze under what structural conditions the judgment\u2013decision-making conversion operates or is blocked has been presented only in limited fashion (Pfeffer & Sutton, 2000; Teece, 2007; Lee, 2025).",

    "441": "The present study takes this gap as the starting point of its analysis. It designates as its central analytical object cases in which judgment was formed but not approved within the organizational context of AI utilization training requests, and redefines Seizing not as \u2018an outcome of decision\u2019 but as \u2018a processual phase that determines whether approval is granted.\u2019 Through this, by theoretically refining the structural conditions under which the judgment\u2013decision-making conversion operates or stalls, the study aims to explain the conversion failures occurring after AI utilization training requests at the level of the operating principles of organizational dynamic capabilities (Teece, 2007).",

    "442": "2.6. Summary",

    "443": "Chapter 2 theoretically repositioned\u2014through the cross-examination of Dynamic Capabilities Theory and AI adoption and utilization research\u2014under what conditions judgments formed within organizations after AI utilization training requests lead to strategic decision-making or stagnate. Its purpose was to systematically review prior research on AI adoption, utilization, and organizational transformation, and to clearly derive the theoretical position and research gap of the present study. To this end, the theoretical development and core concepts of Dynamic Capabilities Theory were first reviewed (2.1), and among these, the Seizing stage\u2014which has been relatively under-analyzed\u2014was reexamined from the perspective of the conversion process between judgment and decision-making (2.2).",

    "444": "In the ensuing discussion (2.3), the validity of adopting case-based theory building and a single-case approach as concrete methodologies for fully capturing the core problematic awareness raised earlier was systematically demonstrated on the basis of prior literature.",

    "445": "Mainstream methodological inquiries have repeatedly emphasized the outstanding analytical utility that case-based approaches possess in dissecting multi-layered organizational phenomena and the micro-level dynamics residing at their depths. In this context, it was reaffirmed that the core inquiry question raised is not one confined to the superficial measurement of whether post hoc outcomes are produced, but rather a task of processual character that traces in depth how internal judgment and final decision-making interconnect or disconnect along what trajectories.",

    "446": "In the subsequent Section 2.4, the principal streams of prior research illuminating the actual adoption and utilization of artificial intelligence technology and the attendant organizational-level transformation mechanisms were comprehensively critiqued and reviewed. These literatures have theoretically emphasized that AI-based technology and related capabilities constitute the pivotal driving force guaranteeing corporate output indicators and sustainable competitive advantage, while simultaneously positioning the supporting technology education and internal learning processes as indispensable prerequisites for organizational dynamic capabilities accumulation.",

    "447": "Nevertheless, these existing discourses harbor a critical limitation. Specifically, it was identified that the elucidation of precisely what organizational conditions and internal coordination procedures judgment established among internal members immediately after AI utilization training is formally requested of the organization must pass through in order to settle into the strategic decision-making trajectory remains at a superficial and limited level.",

    "448": "In the subsequent Section 2.5, drawing upon the trajectory of the preceding literature review, the critical research gap that must be squarely confronted was derived through the intersection of the epistemological perspectives of the Knowing\u2013Doing Gap concept and the Seizing mechanism. As is well established, existing literatures have explained the discordance and delay states arising between the will to utilize technology and actual outcome production primarily as attributable to the implementing department\u2019s deficiency in execution capacity, structural constraints on internal resources, or uncontrollable exogenous variables.",

    "449": "Yet the identification of micro-level mechanisms explaining why meaningful judgments incubated in the organizational depths after training procedures have unfolded fail to transform into formal decision-making possessing binding force was severely omitted. Above all, given that even within Dynamic Capabilities Theory itself the Seizing stage tends to be reduced and summarized as a product of fragmentary strategic resolution, it was clearly revealed that an enormous theoretical blind spot has been left unattended with respect to elucidating the underlying internal structures and operating conditions governing the conversion phase between judgment and decision-making.",

    "450": "Consequently, the series of critical reviews developed in the present chapter converges upon a single point. Namely, the fundamental question\u2014\u2018Why does judgment built from the AI utilization training request as a starting point fall into a state of stagnation without entering the internal institutional approval system?\u2019\u2014constitutes the critical unexplored inquiry domain that has not been fully elucidated within the boundaries of prior research.",

    "451": "Accordingly, departing from the conventional perspective, the complex conversion phase from judgment to decision-making is comprehensively repositioned as the substantive core operating mechanism of Seizing, and the structural conditions within the organization that determine whether ultimate approval is granted are elevated to independent analytical units.",

    "452": "In the following chapter, a concrete research design is structured on the basis of this newly established theoretical realignment. Furthermore, by transparently presenting the procedures for in-depth data collection and analysis, the trajectory from the initial incubation of judgment to the ultimate frustration of the approval process is meticulously traced\u2014grounded in the empirical realities of the field\u2014to illuminate through what causal pathways it manifests.",
}

save_batch('translations_ch2_batch2.json', T)
