"""Chapter 2 Batch 1: P389-P420 (Literature Review: DC Theory, Seizing Microfoundations, Case-based Theory Building, AI Adoption start)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from save_translations import save_batch

T = {
    "389": "CHAPTER 2\n\nLITERATURE REVIEW",

    "390": "2.1. Theoretical Development of Dynamic Capabilities Theory",

    "391": "Dynamic Capabilities Theory constitutes a theoretical framework that explains how organizations maintain strategic fitness by rearranging and reconfiguring their resources\u2014beyond merely \u2018possessing\u2019 them\u2014under conditions where technological change and environmental uncertainty have become routine (Teece, Pisano, & Shuen, 1997; Teece, 2007). This theory emerged from the problematic awareness of extending the Resource-Based View (RBV), which had focused on the scarcity and inimitability of internal resource holdings under the assumption of relatively stable environments (Teece, Pisano, & Shuen, 1997). The departure point of the dynamic capabilities discourse was the recognition that performance is determined not by resource possession per se, but by the ability to redeploy and adjust those resources within changing environments (Teece et al., 1997).",

    "392": "Teece, Pisano, and Shuen (1997) defined dynamic capabilities as the ability of firms to integrate and reconfigure internal and external competences in response to rapidly changing environments. This definition signifies a theoretical shift in that it conceptualizes capabilities not as fixed assets but as organizational abilities that are continuously adjusted in response to environmental change. In other words, dynamic capabilities focus not on \u2018what is possessed\u2019 but on \u2018how the organization responds and reorganizes\u2019 (Teece et al., 1997).",

    "393": "Subsequently, Teece (2007) did not regard dynamic capabilities as a singular, monolithic ability but rather explained them as distinct functional phases that manifest as organizations respond to environmental change (Teece, 2007). He presented these as three activity categories\u2014Sensing, Seizing, and Transforming\u2014although this taxonomy is understood not as mechanistically sequential stages proceeding in temporal order, but rather as operational domains that iteratively intersect within the process of strategic response (Teece, 2007).",

    "394": "This tripartite distinction can more clearly reveal the operational logic of the theory when unpacked through three analytical questions: \u2018What is sensed (Sensing)? What choice is committed to (Seizing)? What is altered to sustain that choice (Transforming)?\u2019\u2014thereby transcending a mere stage-enumerative description (Teece, 2007).",

    "395": "Sensing is understood not as the mere collection of external information, but as the process of discerning which elements among signals of change demand strategic choice by the organization and converting their meaning through internal interpretive frameworks (Teece, 2007). Seizing refers to the phase in which such interpretations are consolidated into formal organizational-level choices and coupled with corresponding resource allocation and accountability structures (Teece, 2007). Transforming is described as the activity of readjusting the organization\u2019s structures, procedures, and asset configurations to render committed choices implementable (Teece, 2007).",

    "396": "Accordingly, it is appropriate to apprehend these three activities not as a fragmented functional catalogue, but as a single processual chain in which interpretation, commitment, and reconfiguration operate in an interlocking manner (Teece, 2007).",

    "397": "Dynamic capabilities are better understood not as a set of specific standardized routines, but as processual abilities that are differentially instantiated according to organizational context. Eisenhardt and Martin (2000) explained dynamic capabilities not as uniformly replicable best practices, but as processes that share a common logic yet manifest differently depending on each organization\u2019s resource composition and environmental conditions (Eisenhardt & Martin, 2000). This perspective suggests that dynamic capabilities research should move beyond outcome-indicator-centered comparison toward the analysis of the processes of formation and operation (Eisenhardt & Martin, 2000).",

    "398": "Nevertheless, the Seizing stage has frequently been abbreviated and explained as the outcome of strategic choice or as the output of resource allocation (Teece, 2007; Eisenhardt & Martin, 2000). While descriptions of what decisions organizations have made do exist, analysis of the pathways through which those decisions are formalized via internal judgment and approval processes has remained relatively limited. This gap may be interpreted as arising from the insufficient accumulation of research designs that microscopically trace these processes, notwithstanding the fact that Seizing actually encompasses complex processes including judgment, legitimation, and responsibility allocation.",

    "399": "Dynamic Capabilities Theory thus provides a macro-level explanatory framework for responding to environmental change, yet it leaves room for further theoretical refinement regarding the internal process by which judgment converts into decision-making at the Seizing stage (Teece, 2007). In particular, the premise that judgment automatically connects to decision-making fails to adequately explain the conversion delay phenomena observed in actual organizational contexts. This problematic awareness raises the necessity of reinterpreting Seizing in a more process-centered manner.",

    "400": "2.2. The Concept of Seizing and Its Microfoundations",

    "401": "Within Dynamic Capabilities Theory, Seizing corresponds to the conversion zone in which an external signal of \u2018opportunity\u2019 solidifies into a \u2018binding choice\u2019 within the organization. Put differently, Seizing is the connective process through which a sensed possibility is aligned into a strategic choice and that choice is rendered into a commitment of resource investment (Teece, 2007).",

    "402": "From this perspective, Seizing approximates not a sub-stage of execution, but rather the domain that constitutes the conditions under which execution becomes possible. For a strategic choice to be established, a judgment regarding what to do must first be formed; that judgment must then be organized into a form of choice that the organization can sustain; and finally, that choice must be confirmed as a commitment to resource allocation. The reason Teece (2007) described Seizing as the phase of opportunity-based choice and resource commitment lies precisely here.",

    "403": "However, a considerable portion of Seizing research has exhibited a tendency to treat this conversion not as \u2018a process requiring explanation\u2019 but as \u2018an already-occurred outcome.\u2019 Eisenhardt and Martin (2000) understood dynamic capabilities not as an inventory of specific routines but as organizational patterns that operate recurrently in changing environments, presenting Seizing as the phase in which strategic choice and resource allocation take place. While this framework positions Seizing at the center of dynamic capabilities, it does not sufficiently secure analytical units for examining how choices converge into organizational-level commitments through internal pathways, or why those pathways stall (Eisenhardt & Martin, 2000).",

    "404": "Teece (2007) attempted to partially address this gap by presenting the microfoundations of Seizing. He viewed Seizing not as a single event but as a complex process in which elements such as cognition, justification, choice, and resource commitment are combined (Teece, 2007). However, these elements are often merely listed as \u2018components,\u2019 and the accumulation of explanations regarding the conditions under which their combination is strengthened, the conditions under which fragmentation occurs, and how such fragmentation becomes entrenched as an organizational state of non-decision has been limited. When discussing microfoundations, the crux lies not in the enumeration of items but in the rules of combination, and these rules have not been sufficiently clarified theoretically (Felin, Foss, & Ployhart, 2015; Teece, 2007).",

    "405": "At this juncture, \u2018judgment\u2019 is invoked repeatedly, yet analysis generally remains confined to individual insight, experience, and cognitive capacity (Teece, 2007; Eisenhardt & Martin, 2000). Consequently, while judgment is acknowledged as central to Seizing, the process through which it is transformed into a \u2018decision-ready form\u2019 by combining with the organization\u2019s internal legitimation structures, responsibility allocation, and agenda-setting rules has been relatively marginalized. At the moment when judgment fails to be articulated in the organization\u2019s language, when the attribution of responsibility becomes unclear, or when agenda-setting is delayed, a state may emerge in which judgment exists yet no decision materializes (Bachrach & Baratz, 1962; Morrison & Milliken, 2000).",

    "406": "Prior research has frequently treated such failures not as independent analytical objects but has summarized them as the fact that choices were ultimately not made. However, non-decision is not merely an \u2018absence\u2019; it may constitute a product of organizational operation occurring along the pathways of agenda-setting, legitimation, and responsibility allocation (Bachrach & Baratz, 1962; Cohen, March, & Olsen, 1972). At this point, the key question shifts from \u2018why was there no choice?\u2019 to \u2018under what conditions does judgment fail to solidify into a decision?\u2019",

    "407": "The present study does not narrowly construe Seizing as \u2018the moment a decision is made,\u2019 but rather repositions it as the entire pathway through which judgment either passes through organizational-level legitimation and approval structures to convert into decision-making, or stagnates prior to that point. From this vantage, Seizing constitutes a mechanism rather than an outcome, and the point at which the judgment\u2013decision-making conversion halts becomes the critical zone that determines the success or failure of Seizing (Teece, 2007). Accordingly, the endeavor to reexamine Seizing from the perspective of the judgment\u2013decision-making conversion mechanism serves as the starting point for restoring the explanatory gap that prior theory has insufficiently addressed to concrete analytical units.",

    "408": "2.3. Case-Based Theory Building and the Single-Case Approach",

    "409": "In Sections 2.1 and 2.2, the present study adopted Seizing within Dynamic Capabilities Theory as its core analytical lens and confirmed the necessity of reconceptualizing Seizing as \u2018the process through which judgment actually leads to, is delayed, or is interrupted in its transition to organizational-level decision-making\u2019 (Teece, 2007; Eisenhardt & Martin, 2000). This problematic awareness calls for analyzing Seizing not as a mere outcome of strategic choice, but as a processual and micro-level conversion mechanism that explains how judgment within organizations fails to convert into formal decision-making and stalls. Accordingly, the present section advances the rationale\u2014grounded in prior research\u2014for adopting case-based theory building and a single-case approach as the means to theoretically capture and refine such mechanisms (Eisenhardt, 1989; Flyvbjerg, 2006).",

    "410": "Case-based theory building is understood as an approach that takes phenomena insufficiently explained by existing theories as its point of departure, analyzes data collected from actual organizational settings, and derives concepts and relationships through that process to form or refine theory (Eisenhardt, 1989). This approach aims not merely at hypothesis testing, but at reconstructing explanatory structures themselves through the processes and patterns revealed in the field (Eisenhardt, 1989).",

    "411": "The primary direction of analysis is not oriented toward the retrospective adjudication of the simplistic question of whether an AI utilization training request directly results in visible organizational outcomes. Rather, fundamental weight is placed on why a judgment that was clearly articulated among organizational members and management, beginning from the training request, fails to converge into the formal decision-making system.",

    "412": "Furthermore, the core of the analysis resides in elucidating in depth precisely at which procedural juncture the said judgment is delayed or structurally stagnated. In other words, transcending the dimension of merely confirming the presence or absence of surface-level outcomes, the processual mechanism itself\u2014through which formed judgments operate while traversing the complex zones of internal approval, legitimation, and deferral within the organization\u2014is rigorously established as the central object of inquiry.",

    "413": "Such a problem formulation presupposes that, rather than cross-sectional research designs centered on performance variables, a case-based approach that can trace the approval structures, responsibility allocation, and agenda-setting delays actually operative within the organization after judgment formation over the course of time is more appropriate (Eisenhardt, 1989). Accordingly, the present study sets the organizational internal operational process following an AI utilization training request as its unit of analysis and seeks to theoretically refine the judgment\u2013decision-making conversion mechanism manifested therein (Eisenhardt, 1989).",

    "414": "In this context, the present study adopts a single-case approach. Single-case research is not a method that attempts generalization through statistical representativeness, but one whose purpose lies in deeply analyzing how concepts and processes operate within a specific organizational context and thereby deriving theoretical generalization (Flyvbjerg, 2006). In the present study, the single case does not simply mean \u2018analyzing only one organization\u2019; rather, it is a deliberate choice aimed at making visible the critical juncture where judgment fails to lead to formal decision-making\u2014that is, the structural point at which the judgment\u2013decision-making conversion stalls or is delayed\u2014through intensive inquiry into a single organization. This approach is congruent with the study\u2019s objective of explaining the conditions under which the sub-processes constituting Seizing connect and disconnect, rather than summarizing Seizing as an outcome (Teece, 2007).",

    "415": "The single-case approach can also be combined with an embedded single-case design that incorporates multiple units of analysis within the case itself (Flyvbjerg, 2006). Indeed, among recent doctoral studies addressing AI adoption and organizational transformation, research has been reported in which a single organization was designated as the single case while multiple AI application instances within the organization served as sub-units of analysis for interview-based qualitative analysis (Ifland, 2023). Ifland (2023) designated the AI initiatives of a German energy supply company as a single case and analyzed interview data using multiple application instances as units of analysis, thereby presenting an analytical framework explaining the logic and conditions under which organizational AI transformation unfolds. Such research demonstrates that qualitative approaches combining single cases with embedded analytical units are actively employed in AI transformation contexts, suggesting that the present study\u2019s case design is connected to recent research trends (Ifland, 2023).",

    "416": "With respect to data analysis strategy, case-based theory building does not regard data acquisition and interpretation as rigidly separated independent stages. Rather, a cyclical trajectory is presupposed in which initial data collection, provisional meaning assignment, subsequent data exploration, and correction of prior interpretations continuously intersect, progressively elevating the theoretical logic (Eisenhardt, 1989). In accordance with this methodological orientation, pluralistic qualitative data\u2014encompassing field interview materials, official organizational documents, and participant observation records\u2014are organically combined to capture, at the mechanism level, the disconnection points where internal organizational judgment fails to transition into strategic decision-making. This analytical choice is deeply consonant with the methodological currents that have been practically adopted in recent qualitative inquiries dissecting AI transformation phenomena (Ifland, 2023).",

    "417": "Finally, the exposition of the present section does not aim to anticipate the specific research methodology that will be fully addressed in the subsequent chapter (Chapter 3). Rather, it concentrates on demonstrating, within the minimal boundaries of the overall literature review context, the theoretical congruence between the newly adopted case-based and single-case inquiry approach and the existing methodological discourses (Eisenhardt, 1989; Flyvbjerg, 2006).",

    "418": "Building upon this establishment of methodological validity, Section 2.4 proceeds to systematically review the principal literature addressing the adoption and utilization of artificial intelligence technology and the attendant organizational transformation. Moreover, in the process of dissecting that literature, it identifies that the judgment\u2013decision-making conversion mechanism inherent in the Seizing stage of Dynamic Capabilities Theory remains insufficiently elucidated, thereby naturally connecting to the discussion of the critical research gap in Section 2.5 (Ifland, 2023; Teece, 2007).",

    "419": "2.4. Prior Research on AI Adoption and Organizational Transformation",

    "420": "2.4.1. Research Streams Understanding AI Adoption as a Catalyst for Organizational Transformation",
}

save_batch('translations_ch2_batch1.json', T)
