"""Chapter 3 Batch 1: P454-P490 (Research Design Overview, Qualitative Approach, Case Selection beginning)"""
import sys, os
sys.path.insert(0, os.path.dirname(__file__))
from save_translations import save_batch

T = {
    "454": "Chapter 3\n\nResearch Methodology",

    "455": "3.1. Research Design Overview",

    "456": "The present study focuses on explaining why judgments formed within an organization following an AI utilization training request fail to be confirmed as strategic decision-making. Accordingly, the center of analysis is placed not on performance variables but on the structural bottlenecks occurring at the point where the approval process is never entered during the judgment\u2013decision-making conversion, and on the operating mechanisms underlying such bottlenecks. In particular, this study treats the state in which no decision has been made (non-decision) not as a mere void but as an analytical outcome that demands its own independent explanation. Such a problem formulation necessitates not a quantitative research design that statistically tests causal relationships among variables, but rather a qualitative research design capable of tracing, over time, the actual operating processes through which judgments are formed, legitimated, deferred, and blocked within the organization.",

    "457": "Accordingly, this study adopts a qualitative single case study as its research strategy. The qualitative single case study has been evaluated as an approach well suited to deriving concepts and relationships grounded in field data and to refining theory for phenomena that existing theories have not sufficiently explained (Eisenhardt, 1989; Yin, 2009). Given that the core interest of this study lies not in the outcome-oriented question of whether AI utilization training produced results, but in the processual question of why decisions that could have led to outcomes were prevented from being made, case-based theory-building research exhibits a high degree of congruence with the purpose of this study.",

    "458": "This study adopts qualitative research methodology, with the case study serving as the core research strategy. Qualitative research methodology encompasses phenomenology, grounded theory, ethnography, narrative inquiry, and case study, among others, each possessing distinct strengths depending on the research purpose and the object of analysis (Creswell, 2018). Because this study aims not to describe the meaning of individual experiences or to inductively generate theory, but rather to explain the processual and structural mechanisms by which judgments fail to be converted into decision-making within the organizational context, the case study approach constitutes the most appropriate methodological choice.",

    "459": "An approach that cross-compares multiple cases to identify variance among specific variables is inadequate for fully addressing the problem consciousness currently posed. What is required to elucidate the phenomenon is not a quantitative expansion of the sample. Rather, what is essential is the meticulous dissection of the micro-level flow through which a particular judgment, despite having been clearly established within a single organizational environment, fails to enter the official approval track and for what reasons. Indeed, as the number of cases subject to analysis increases, the concrete trajectory underlying the frustration of conversion is at considerable risk of being diluted on the surface. Ultimately, the single-case design of this study is not a compromise intended to secure representativeness of the population; it is a core analytical strategy deliberately intended to capture in depth the precise operational point at which the conversion between judgment and decision-making comes to a halt (Yin, 2009).",

    "460": "Furthermore, the target of inquiry is not placed on tracking changes in the subjective attitudes of individual members. The true focus of analysis lies in illuminating the structural form of judgment that is collectively shared and reproduced within the organization, as well as the processual trajectory through which that judgment either safely passes through or is structurally blocked at specific junctures within the organization's multi-layered approval system. In this context, the field interview data collected are likewise not employed to describe the inner psychology of individual actors. Rather, they are rigorously treated as critical empirical clues for objectively reconstructing how the macro-level meaning network at the organizational level is constructed and how the judgment\u2013decision conversion structure actually stagnates or operates in practice.",

    "461": "As the theoretical framework, Dynamic Capabilities Theory is applied, with particular attention directed to the Seizing stage. In existing discussions, Seizing has tended to be compressed into the result of strategic choice having been made (Teece, 2007; Eisenhardt & Martin, 2000); however, this study reconceptualizes it as a matter of the process through which judgments are either confirmed as or suspended from becoming official decisions.",

    "462": "Data analysis does not presuppose a linear stage distinction. Interpretation occurs simultaneously with data collection, and provisional explanations are iteratively adjusted through additional data (Eisenhardt, 1989). Within this cyclical structure, it is revealed how the state of non-conversion into decision is sustained.",

    "463": "The explanatory propositions of this study are not propositions intended for statistical testing but rather interpretive devices for connecting the phenomena observed within the case to organizational-level mechanisms. The propositions function not as fixed premises but as analytical tools that are modified by the data.",

    "464": "Finally, this study takes AIDA (University of Glasgow, 2025) as its anchor study. Whereas the AIDA study elucidated the disconnection between organizational judgment and decision-making in a digital and AI context at the mechanism level, this study extends that analysis to the organizational judgment structure following an AI utilization training request, thereby reconceptualizing the operating conditions of the Seizing stage in more concrete terms. In other words, by applying the analytical logic of AIDA to an educational context, this study expands the theoretical scope for explaining the failure of judgment\u2013decision-making conversion.",

    "465": "3.2. Qualitative Research Approach and Single-Case Study Design",

    "466": "The primary purpose of this inquiry does not lie in retrospectively verifying the visible effects or final outcomes produced by an AI utilization training request. Rather, the center of analysis is placed on dissecting, in the phase prior to the training request being actually implemented, through precisely what internal trajectory the judgment clearly established within the organization failed to result in official decision-making. In accordance with this context, a quantitative analytical design focused on measuring derived outcome variables is entirely excluded. Instead, a qualitative research approach is adopted, one capable of hermeneutically tracing how the continuous process\u2014in which judgment is initially conceived and either secures legitimacy or is delayed and deferred at specific points of impasse\u2014is woven and sustained within the organizational network.",

    "467": "The qualitative mode of inquiry eschews the practice of reducing complex social and organizational phenomena into mechanical variables predetermined by the researcher for quantification. Rather, it is oriented toward capturing in depth the meaning systems that internal actors construct within a particular environmental context, and the dynamic process through which such meanings are formed and transformed (Creswell, 2018). Above all, the currently investigated state\u2014in which judgment clearly exists yet no official decision has been opened\u2014constitutes an eminently processual phenomenon that is exceedingly difficult to immediately reduce to simple numbers. Consequently, for elucidating this phenomenon, the qualitative approach provides overwhelmingly superior theoretical explanatory power.",

    "468": "As an extension of this qualitative orientation, the case study is introduced as the core analytical strategy for probing the phenomenon. Case-based inquiry has been recognized as the most excellent methodological tool for meticulously dissecting the multi-layered causal networks and micro-level operating mechanisms intertwined behind the phenomenon while fully preserving the specific context of the field in which the phenomenon manifested (Eisenhardt, 1989; Yin, 2009).",

    "469": "The logical rationale for placing the concrete case study as the core axis of analysis unfolds as follows. First, the fundamental question currently posed does not reside in the consequentialist determination of whether AI utilization training produced substantive outcomes. Rather, it is rooted in a thoroughly process-oriented problem consciousness that probes why, despite the organizational-level judgment regarding the introduction of such training having been clearly established, it failed to enter the official decision-making track that would guarantee implementation. The task of elucidating such intimate internal dynamics cannot be fully accomplished through an approach that flatly contrasts multiple samples to describe superficial gaps among variables. Rather, a case study approach that three-dimensionally reconstructs, at the deep level of a single organizational ecosystem, how and along what temporal trajectory the conversion segment between judgment and decision comes to a halt and stagnates, secures far stronger methodological validity.",

    "470": "Second, this study does not aim at statistical generalization through multiple cases. Instead, by refining the judgment\u2013decision-making conversion stagnation observed in a single case into theoretical concepts and propositions, it sets as its research objective the provision of a theoretical generalization\u2014an explanatory framework that can be examined in similar organizational contexts (Eisenhardt, 1989; Yin, 2009). In light of this research purpose, the single case study is not a limitation of representativeness but a strategic choice to secure the focus and depth of analysis.",

    "471": "Third, the case addressed in this study is one in which an AI utilization training request did not enter the actual implementation stage, which distinguishes it analytically from the post-implementation outcome comparison studies that existing research has predominantly analyzed. In this case, the organizational-level judgment regarding the necessity of the AI utilization training request was officially formed and approved; however, the procedure for connecting this to an implementation decision was never initiated, and this state of non-initiation persisted. Such a state of non-activation is evaluated as a case that is theoretically particularly suitable for analyzing the operating conditions of the Seizing stage.",

    "472": "The single-case inquiry of this study does not aim to measure changes in the psychological attitudes of individual members or fragmentary learning outcomes. Rather, the true focus of analysis is calibrated to the macro-level and organizational conditions governing the conversion segment between judgment and decision-making\u2014the structure of judgment collectively constructed within the organization, the absence of formal procedural pathways, and the ambiguity of authority and responsibility attribution. In this context, the field-collected individual interviews and utterance records are rigorously treated not as independent objects of analysis for describing the inner world of individual subjects, but as empirical clues that objectively attest to how the organizational-level meaning network and judgment system are constructed and maintained.",

    "473": "This inquiry design adopts the cognitive framework of Dynamic Capabilities Theory\u2014specifically, the Seizing stage\u2014as the core theoretical lens for dissecting the phenomenon. As is well known, conventional Dynamic Capabilities discourses have concentrated on the Sensing and Transforming phases, thereby exposing clear limitations in fully elucidating the micro-level operating principles underlying the Seizing stage, where conceived judgments transition into substantive organizational decisions and choices (Eisenhardt & Martin, 2000; Teece, 2007). Accordingly, this study departs from the perspective that reduces Seizing to a mere product of strategic decision and instead fully redefines it as a complex processual phase in which formed judgments either obtain official institutional approval or are structurally blocked, and meticulously dissects this within the concrete field context of an AI utilization training request.",

    "474": "Consequently, the qualitative inquiry orientation and the adoption of the single-case design taken by this study are by no means a compromise arising from the mere convenience of research execution or the practical constraints of securing field data. This is the outcome of a highly theoretical and methodological determination deeply rooted in the essential character of the inquiry question that has been rigorously formulated and in the unique characteristics of the phenomenon to be elucidated. Furthermore, this methodological foundation functions as a core design precondition that firmly supports the validity of the specific case selection and the coherence of the data analysis procedures that will be developed subsequently.",

    "475": "Going one step further, this structured single-case inquiry design, by organically combining with the specific case selection logic of the ensuing Section 3.3, simultaneously establishes both the methodological imperative of why a single-case approach is necessary and the empirical validity of why this particular case deserves attention. In other words, the object of analysis in this study is not a sample adopted simply because of the researcher's physical accessibility. Rather, it constitutes a revelatory case that permits the observation, at a deep level, of the structural operating conditions unique to the Seizing stage\u2014where organizational judgment has been clearly established yet the track of official decision has not been fully opened\u2014thereby substantively amplifying the theoretical explanatory power and legitimacy of the single-case design (Yin, 2009).",

    "476": "3.3. Case Selection Rationale",

    "477": "To meticulously dissect at the micro-level mechanism the process of disconnection by which judgment conceived within the organization, triggered by an AI utilization training request, fails to enter the track of official decision-making, a qualitative single case study design is fully adopted. This methodological choice thoroughly eschews the quantitative objective of securing the statistical representativeness of the sample. Rather, its fundamental purpose lies in deriving theoretical generalization applicable to similar contexts by probing in depth how concepts and actual processes interlock and operate within a specific organizational ecosystem (Yin, 2009).",

    "478": "Under this purpose, a nonprofit religious organization designated as Organization A (pseudonym), located in South Korea, is selected as the core case for analysis. The organization under analysis is a nonprofit organization\u2014a small-to-medium-scale institution possessing an official decision-making structure (approval system, personnel committee, etc.). For the purposes of organizational security and anonymity protection, detailed names, founding year, and exact personnel size are not disclosed. However, to facilitate the assessment of Transferability for this study, it is stated that the case organization satisfies the following conditions: (1) it operates a formal approval system, (2) it possesses official decision-making bodies such as a personnel committee, and (3) it has begun to internally share the necessity of strengthening AI utilization capabilities. At the field site of this organization, a formal request for AI utilization training was initiated by an internal member group, and this request successfully passed through the formal approval process via the organization's official authorization line.",

    "479": "Nevertheless, despite such clear institutional approval having been obtained, the said agenda item was unable to proceed at all to actual educational program planning, concrete implementation, or any subsequent decision-making to support these, and has remained fixated in a state of prolonged structural stagnation.",

    "480": "The reason for focusing intensively on this particular case is by no means to point out the superficial phenomenon of implementation delay or a simple administrative oversight by the relevant department. Rather, it is because this case provides an optimal analytical scene capable of vividly capturing the micro-level operating principles underlying how judgment clearly established at the organizational level is obstructed by specific institutional limitations and procedural conditions and thereby fails to leap to the final decision-making stage.",

    "481": "For this reason, the present case is classified as a revelatory case (Yin, 2009). A revelatory case refers to an instance in which internal operating mechanisms\u2014which were difficult to observe under conventional research approaches or typical organizational studies\u2014become relatively clearly manifest under specific conditions (Yin, 2009). In the present case, although the AI utilization training request was submitted and approved as an official document, it was subsequently confirmed that the said agenda item was effectively treated as being in a state of non-existence within the organization's internal system. This is significant in that it enables the empirical tracing of the process by which judgment, even after being formed, is maintained in a state of Non-decision without being connected to the official decision-making structure, thereby providing important empirical clues for analyzing the Seizing stage of Dynamic Capabilities Theory.",

    "482": "Furthermore, the case possesses the advantage of enabling the organic combination and dissection of pluralistic data sources\u2014official internal documents, electronic approval system records, the state of absent explicit replies, and participant observation records directly conducted by the researcher. Through this, the structural bottlenecks and points of disconnection situated in the segment transitioning from judgment to decision-making can be illuminated more three-dimensionally. Above all, the fact that despite a clear external stimulus (trigger) in the form of AI utilization training having been applied, the organization's official discussion table was never convened, no responsible party was assigned, and follow-up procedures were entirely suspended, serves as powerful empirical evidence that critically compels the reexamination of the existing tacit premise that the Seizing phase will unconditionally be activated.",

    "483": "At the same time, the fact that the current object of analysis is situated within the specific context of a nonprofit religious organization must not be treated as an exceptional phenomenon confined solely to that context. Rather, it represents a reality that can manifest quite universally across numerous similar organizational ecosystems in South Korea\u2014those possessing complex multi-tier approval lines, where the attribution of authority and responsibility is ambiguous, and where the informal drifting and deferral of specific agenda items is prevalent. Consequently, this case is evaluated as possessing not only a revelatory character that fully exposes the underlying dynamics of the phenomenon, but also simultaneously securing the value of a typical case endowed with broad structural representativeness.",

    "484": "Finally, the significance of selecting this case does not lie in evaluating the success or failure of a specific organization. The purpose of this study lies in deriving, beyond the particularities of the case organization, theoretical mechanisms that explain how judgments are formed within the organization following an AI utilization training request and under what structural and procedural conditions they fail to be converted into decision-making. Therefore, the analytical results presented in this study are oriented not toward statistical generalization but toward theoretical generalization aimed at explaining the micro-level operating logic of the Seizing stage (Eisenhardt, 1989; Yin, 2009).",

    "485": "The dates of generation for the data utilized in this study are as follows: Appendix A (the training request official document) is dated December 24, 2025; Appendices B and C (external consulting reports) are dated July 2025; and Appendix D (electronic approval system record queries) are dated January 22 and February 9, 2026. Accordingly, the effective tracking period of the core events is approximately six to seven weeks, and this constitutes a condition that must be considered in conjunction with the discussion of this study's methodological characteristics and limitations (see Section 6.6).",

    "486": "3.4. Data Collection",

    "487": "To trace step by step, within the concrete case context, the process by which judgment formed within the organization following an AI utilization training request fails to be converted into organizational-level decision-making, this study adopts a collection strategy that reconstructs records generated over the flow of time in a sequential chain, rather than arranging data types in parallel. Here, multiple data sources refers to a strategy that does not rely on a single data type but rather cross-utilizes data of differing natures\u2014official documents, electronic approval system records, the state of absent replies, and the researcher's participant observation data\u2014to perform mutually complementary verification of the same phenomenon (Yin, 2009). This approach functions as an analytical device for tracing the points where conversion did not occur by comparing and contrasting the time points at which each datum was generated and their procedural positions (Eisenhardt, 1989).",

    "488": "In the present case, it is clearly confirmed that even after the AI utilization training request was officially approved and one or more official personnel committee schedules had elapsed, the said agenda item failed to enter the organizational-level decision-making flow. This acquires critical analytical significance in that the core phenomenon to be elucidated is not a matter of short-term administrative delay or an accidental omission by a working-level department, but rather a structural state of non-entry that was repeatedly captured within the organization's official decision-making cycle.",

    "489": "This empirical factual determination was rigorously derived through the process of cross-confirming the initial official document approval record and the complete absence of subsequent decision-making procedures that should have followed thereafter (see Appendix A and Appendix D).",

    "490": "Consequently, the failure of conversion between judgment and decision-making is not regarded as a singular event that occurred in isolation. Rather, it is understood as a cumulative process that exposes the state in which a specific agenda item was structurally never invoked throughout the period during which the organization's decision procedures repeatedly cycled, and it is precisely this point that is firmly established as the core unit of analysis for elucidating the phenomenon."
}

save_batch('translations_ch3_batch1.json', T)
